# **BITÁCORAS**
*Grupo 2, Sección 3*

Integrantes:
*   Francisco Díaz Aguilar
*   Joseph Delgado
*   Felipe Contreras
*   Luis Cerda

# **FP01. Introducción a Python**
JOSEPH DELGADO CARDOZO

## Descripción del notebook

pendiente de confirmación en Miró

sdf

## <font color='purple'>__Material adicional__</font>

7 o más

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('https://youtu.be/GpdPvpV7MkA')

<font color='purple'>Fin material adicional </font>


## <font color='purple'> __EXPERIMENTO__: </font>

### Creación de una serie a partir de un `array` de Numpy.

7 o más

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(type (a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [ ]:
s2 = pd.Series(a)
s2

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#  Le creamos un índice
s3 = pd.Series(a, index=['A', 'B', 'C', 'D'])
s3

A    1
B    2
C    3
D    4
dtype: int64

Veamos qué pasa si le cambiamos el tipo de datos al array

In [ ]:
b = np.array([1, 2, 3, 4], dtype=np.float16)
print(type (b))
b

<class 'numpy.ndarray'>


array([1., 2., 3., 4.], dtype=float16)

In [ ]:
# y creamos una Serie
s4 = pd.Series(b, index=['A', 'B', 'C', 'D'])
s4

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float16

<font color='purple'>Fin experimento </font>

### Creación de una serie a partir de un diccionario

Si partimos de un diccionario para crear la serie:


In [ ]:
d = {"Ene":7, "Feb":5, "Mar":3}
s = pd.Series(d)
s

Ene    7
Feb    5
Mar    3
dtype: int64

El constructor utiliza las claves como etiquetas del índice, y los valores del diccionario como valores de la serie.

Si incluimos el índice explícitamente en el constructor, los valores en la serie se tomarán en el orden en el que estén en el índice explícito. Además, si en éste hay valores que no pertenecen al conjunto de claves del diccionario, se añaden a la serie con un valor *NaN*:

In [ ]:
d = {"Ene":7, "Feb":5, "Mar":3}
s = pd.Series(d, index = ["Abr", "Mar", "Feb", "Ene"])
s

Abr    NaN
Mar    3.0
Feb    5.0
Ene    7.0
dtype: float64

En este ejemplo, hemos creado la serie especificando el índice que hemos formado dando la vuelta a las claves del diccionario ("Mar", "Feb" y "Ene") y hemos añadido a la lista de etiquetas el valor "Abr", que no pertenece al conjunto de claves del diccionario. Se ha añadido a la serie, pero se le ha asignado el valor *NaN*. Es precisamente la presencia de este valor lo que modifica el tipo de la serie a float.

## <font color='green'>Actividades del notebook </font>

### Actividad 1

In [ ]:
#Solución

años = [2015,2016,2017,2018,2019,2020]
sales = [10000,25000,30000,20000,35000,15000]
sales_serie = pd.Series(sales, años)
inicio = int(input('Ingrese año inicio: '))
fin = int(input('Ingrese año fin: '))
a = 0;
for i in range(0,6):
    if inicio == años[i]:
       a = i
    elif fin == años[i]:
       b = i
       print('Ventas antes del descuento: ')
       for j in range(a,b+1):
           print(sales_serie[años[j]])
       print('Ventas con el descuento aplicado: ')
       for k in range(a,b+1):
          desc =(sales_serie[años[k]])*0.9
          print(desc)


Ingrese año inicio: 2015
Ingrese año fin: 2020
Ventas antes del descuento: 
10000
25000
30000
20000
35000
15000
Ventas con el descuento aplicado: 
9000.0
22500.0
27000.0
18000.0
31500.0
13500.0


<font color='green'>Fin Actividad 1</font>

## <font color='purple'>__REFLEXIÓN GRUPAL__:<br>

confirmar si: es por notebook o al finaaaaal de todo (terminando el Módulo)

La analítica de datos ha avanzado considerablemente en los últimos años y ahora existen diversas herramientas que nos permiten realizar tareas o procesos que antes eran complicados de realizar. Gracias a su versatilidad, el lenguaje de programación Python posee una serie de librerías que permiten realizar proyectos de analítica de datos de una forma muy sencilla y una de las librerías más populares es Pandas. En este curso tuvimos la oportunidad de enfocamos en:

* Conocer los conceptos, métodos y funciones de la librería Pandas.
* Analizar datos con la librería de Pandas de forma rápida y sencilla.
* Usar la librería de Pandas para importar, construir y manipular Series y DataFrames.
* Comprobar que la librería Pandas en muy similar al uso de Excel, pero nos permite desarrollar actividades más complejas y con un mayor volúmen de datos.

__Funcionalidad y capacidades:__ Pandas es una biblioteca de análisis y manipulación de datos extremadamente poderosa en Python. Su funcionalidad incluye la capacidad de cargar, limpiar, transformar y analizar datos de manera eficiente. También ofrece numerosas funciones para realizar operaciones estadísticas y de agregación en conjuntos de datos.

__Rendimiento y escalabilidad:__ Pandas está diseñado para manejar grandes volúmenes de datos de manera eficiente. Sin embargo, al trabajar con conjuntos de datos muy grandes, es posible que se requieran técnicas adicionales, como el uso de muestras o la optimización de código, para mejorar el rendimiento. Escala de forma eficiente con otras librerías tales como Dask.

__Documentación y comunidad de usuarios:__ Pandas cuenta con una excelente documentación oficial, que incluye una guía de usuario completa, tutoriales y ejemplos de código. Además, la comunidad de usuarios de pandas es activa y colaborativa, lo que significa que hay una amplia gama de recursos y fuentes de ayuda disponibles en línea.

__Mantenimiento y actualizaciones:__ Pandas es una biblioteca madura y bien mantenida, con una comunidad de desarrollo activa. El equipo de Pandas lanza regularmente nuevas versiones que corrigen errores, agregan nuevas características y mejoran el rendimiento.

__Compatibilidad y integración:__ Pandas se integra bien con otras bibliotecas y herramientas de análisis de datos en el ecosistema de Python, como NumPy, matplotlib, Dask y scikit-learn. También es compatible con una variedad de formatos de datos, lo que facilita la importación y exportación de datos desde y hacia otras fuentes.

__Curva de aprendizaje y facilidad de uso:__ Pandas tiene una curva de aprendizaje moderada, especialmente si tienes experiencia previa con Python y estructuras de datos tabulares. La sintaxis y las operaciones de pandas pueden requerir cierta familiarización, pero una vez que te acostumbras, se vuelve una herramienta potente y flexible.

__Flexibilidad y personalización:__ Pandas ofrece una amplia gama de funcionalidades y opciones de configuración para adaptarse a diferentes requisitos y escenarios de análisis de datos. Además, Pandas es altamente extensible y permite el desarrollo de funciones personalizadas para satisfacer necesidades específicas (e.g.; métodos `apply()`y `map()`).

__Trabajo futuro__: Como equipo creemos que debemos seguir profundizando en el conocimiento de Pandas en los siguientes aspectos:
* Escalado a grandes volúmenes de datos con Dask
* Entender las dinámicas de la librería de forma tal de optimizar el rendimiento de ciertas tareas.
* Profundizar en el uso de tablas dinámicas y el uso de `loc` e `iloc`.
* Explorar más casos de usos avanzados.
* Incorporarnos a una comunidad de usuarios.

<font color='purple'>Fin reflexión grupal</font>

# **FP02. Imprimiendo en Python**
FELIPE CONTRERAS

## Descripción del notebook

pendiente de confirmación en Miró

sdf

## <font color='purple'>__Material adicional__</font>
En el siguiente video se explica la forma en que se pueden crear Dataframes en Pandas.

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('https://youtu.be/GpdPvpV7MkA')

<font color='purple'>Fin material adicional </font>


## <font color='purple'> __EXPERIMENTO__: </font>

### Creación de una serie a partir de un `array` de Numpy.
La celda anterior enuncia que podríamos haber creado una serie a partir de un array NumPy; desarrollamos ese ejemplo.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(type (a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [ ]:
s2 = pd.Series(a)
s2

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#  Le creamos un índice
s3 = pd.Series(a, index=['A', 'B', 'C', 'D'])
s3

A    1
B    2
C    3
D    4
dtype: int64

Veamos qué pasa si le cambiamos el tipo de datos al array

In [ ]:
b = np.array([1, 2, 3, 4], dtype=np.float16)
print(type (b))
b

<class 'numpy.ndarray'>


array([1., 2., 3., 4.], dtype=float16)

In [ ]:
# y creamos una Serie
s4 = pd.Series(b, index=['A', 'B', 'C', 'D'])
s4

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float16

<font color='purple'>Fin experimento </font>

### Creación de una serie a partir de un diccionario

Si partimos de un diccionario para crear la serie:


In [ ]:
d = {"Ene":7, "Feb":5, "Mar":3}
s = pd.Series(d)
s

Ene    7
Feb    5
Mar    3
dtype: int64

El constructor utiliza las claves como etiquetas del índice, y los valores del diccionario como valores de la serie.

Si incluimos el índice explícitamente en el constructor, los valores en la serie se tomarán en el orden en el que estén en el índice explícito. Además, si en éste hay valores que no pertenecen al conjunto de claves del diccionario, se añaden a la serie con un valor *NaN*:

In [ ]:
d = {"Ene":7, "Feb":5, "Mar":3}
s = pd.Series(d, index = ["Abr", "Mar", "Feb", "Ene"])
s

Abr    NaN
Mar    3.0
Feb    5.0
Ene    7.0
dtype: float64

En este ejemplo, hemos creado la serie especificando el índice que hemos formado dando la vuelta a las claves del diccionario ("Mar", "Feb" y "Ene") y hemos añadido a la lista de etiquetas el valor "Abr", que no pertenece al conjunto de claves del diccionario. Se ha añadido a la serie, pero se le ha asignado el valor *NaN*. Es precisamente la presencia de este valor lo que modifica el tipo de la serie a float.

## <font color='green'>Actividades del notebook </font>

### Actividad 1

In [ ]:
#Solución

años = [2015,2016,2017,2018,2019,2020]
sales = [10000,25000,30000,20000,35000,15000]
sales_serie = pd.Series(sales, años)
inicio = int(input('Ingrese año inicio: '))
fin = int(input('Ingrese año fin: '))
a = 0;
for i in range(0,6):
    if inicio == años[i]:
       a = i
    elif fin == años[i]:
       b = i
       print('Ventas antes del descuento: ')
       for j in range(a,b+1):
           print(sales_serie[años[j]])
       print('Ventas con el descuento aplicado: ')
       for k in range(a,b+1):
          desc =(sales_serie[años[k]])*0.9
          print(desc)


Ingrese año inicio: 2015
Ingrese año fin: 2020
Ventas antes del descuento: 
10000
25000
30000
20000
35000
15000
Ventas con el descuento aplicado: 
9000.0
22500.0
27000.0
18000.0
31500.0
13500.0


<font color='green'>Fin Actividad 1</font>

## <font color='purple'>__REFLEXIÓN GRUPAL__:<br>

confirmar si: es por notebook o al finaaaaal de todo (terminando el Módulo)

La analítica de datos ha avanzado considerablemente en los últimos años y ahora existen diversas herramientas que nos permiten realizar tareas o procesos que antes eran complicados de realizar. Gracias a su versatilidad, el lenguaje de programación Python posee una serie de librerías que permiten realizar proyectos de analítica de datos de una forma muy sencilla y una de las librerías más populares es Pandas. En este curso tuvimos la oportunidad de enfocamos en:

* Conocer los conceptos, métodos y funciones de la librería Pandas.
* Analizar datos con la librería de Pandas de forma rápida y sencilla.
* Usar la librería de Pandas para importar, construir y manipular Series y DataFrames.
* Comprobar que la librería Pandas en muy similar al uso de Excel, pero nos permite desarrollar actividades más complejas y con un mayor volúmen de datos.

__Funcionalidad y capacidades:__ Pandas es una biblioteca de análisis y manipulación de datos extremadamente poderosa en Python. Su funcionalidad incluye la capacidad de cargar, limpiar, transformar y analizar datos de manera eficiente. También ofrece numerosas funciones para realizar operaciones estadísticas y de agregación en conjuntos de datos.

__Rendimiento y escalabilidad:__ Pandas está diseñado para manejar grandes volúmenes de datos de manera eficiente. Sin embargo, al trabajar con conjuntos de datos muy grandes, es posible que se requieran técnicas adicionales, como el uso de muestras o la optimización de código, para mejorar el rendimiento. Escala de forma eficiente con otras librerías tales como Dask.

__Documentación y comunidad de usuarios:__ Pandas cuenta con una excelente documentación oficial, que incluye una guía de usuario completa, tutoriales y ejemplos de código. Además, la comunidad de usuarios de pandas es activa y colaborativa, lo que significa que hay una amplia gama de recursos y fuentes de ayuda disponibles en línea.

__Mantenimiento y actualizaciones:__ Pandas es una biblioteca madura y bien mantenida, con una comunidad de desarrollo activa. El equipo de Pandas lanza regularmente nuevas versiones que corrigen errores, agregan nuevas características y mejoran el rendimiento.

__Compatibilidad y integración:__ Pandas se integra bien con otras bibliotecas y herramientas de análisis de datos en el ecosistema de Python, como NumPy, matplotlib, Dask y scikit-learn. También es compatible con una variedad de formatos de datos, lo que facilita la importación y exportación de datos desde y hacia otras fuentes.

__Curva de aprendizaje y facilidad de uso:__ Pandas tiene una curva de aprendizaje moderada, especialmente si tienes experiencia previa con Python y estructuras de datos tabulares. La sintaxis y las operaciones de pandas pueden requerir cierta familiarización, pero una vez que te acostumbras, se vuelve una herramienta potente y flexible.

__Flexibilidad y personalización:__ Pandas ofrece una amplia gama de funcionalidades y opciones de configuración para adaptarse a diferentes requisitos y escenarios de análisis de datos. Además, Pandas es altamente extensible y permite el desarrollo de funciones personalizadas para satisfacer necesidades específicas (e.g.; métodos `apply()`y `map()`).

__Trabajo futuro__: Como equipo creemos que debemos seguir profundizando en el conocimiento de Pandas en los siguientes aspectos:
* Escalado a grandes volúmenes de datos con Dask
* Entender las dinámicas de la librería de forma tal de optimizar el rendimiento de ciertas tareas.
* Profundizar en el uso de tablas dinámicas y el uso de `loc` e `iloc`.
* Explorar más casos de usos avanzados.
* Incorporarnos a una comunidad de usuarios.

<font color='purple'>Fin reflexión grupal</font>

# **FP03. Numbers**
FRANCISCO DÍAZ

## Descripción del notebook

pendiente de confirmación en Miró

sdf

## <font color='purple'>__Material adicional__</font>
En el siguiente video se explica la forma en que se pueden crear Dataframes en Pandas.

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('https://youtu.be/GpdPvpV7MkA')

<font color='purple'>Fin material adicional </font>


## <font color='purple'> __EXPERIMENTO__: </font>

### Creación de una serie a partir de un `array` de Numpy.
La celda anterior enuncia que podríamos haber creado una serie a partir de un array NumPy; desarrollamos ese ejemplo.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(type (a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [ ]:
s2 = pd.Series(a)
s2

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#  Le creamos un índice
s3 = pd.Series(a, index=['A', 'B', 'C', 'D'])
s3

A    1
B    2
C    3
D    4
dtype: int64

Veamos qué pasa si le cambiamos el tipo de datos al array

In [ ]:
b = np.array([1, 2, 3, 4], dtype=np.float16)
print(type (b))
b

<class 'numpy.ndarray'>


array([1., 2., 3., 4.], dtype=float16)

In [ ]:
# y creamos una Serie
s4 = pd.Series(b, index=['A', 'B', 'C', 'D'])
s4

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float16

<font color='purple'>Fin experimento </font>

### Creación de una serie a partir de un diccionario

Si partimos de un diccionario para crear la serie:


In [ ]:
d = {"Ene":7, "Feb":5, "Mar":3}
s = pd.Series(d)
s

Ene    7
Feb    5
Mar    3
dtype: int64

El constructor utiliza las claves como etiquetas del índice, y los valores del diccionario como valores de la serie.

Si incluimos el índice explícitamente en el constructor, los valores en la serie se tomarán en el orden en el que estén en el índice explícito. Además, si en éste hay valores que no pertenecen al conjunto de claves del diccionario, se añaden a la serie con un valor *NaN*:

In [ ]:
d = {"Ene":7, "Feb":5, "Mar":3}
s = pd.Series(d, index = ["Abr", "Mar", "Feb", "Ene"])
s

Abr    NaN
Mar    3.0
Feb    5.0
Ene    7.0
dtype: float64

En este ejemplo, hemos creado la serie especificando el índice que hemos formado dando la vuelta a las claves del diccionario ("Mar", "Feb" y "Ene") y hemos añadido a la lista de etiquetas el valor "Abr", que no pertenece al conjunto de claves del diccionario. Se ha añadido a la serie, pero se le ha asignado el valor *NaN*. Es precisamente la presencia de este valor lo que modifica el tipo de la serie a float.

## <font color='green'>Actividades del notebook </font>

### Actividad 1

In [ ]:
#Solución

años = [2015,2016,2017,2018,2019,2020]
sales = [10000,25000,30000,20000,35000,15000]
sales_serie = pd.Series(sales, años)
inicio = int(input('Ingrese año inicio: '))
fin = int(input('Ingrese año fin: '))
a = 0;
for i in range(0,6):
    if inicio == años[i]:
       a = i
    elif fin == años[i]:
       b = i
       print('Ventas antes del descuento: ')
       for j in range(a,b+1):
           print(sales_serie[años[j]])
       print('Ventas con el descuento aplicado: ')
       for k in range(a,b+1):
          desc =(sales_serie[años[k]])*0.9
          print(desc)


Ingrese año inicio: 2015
Ingrese año fin: 2020
Ventas antes del descuento: 
10000
25000
30000
20000
35000
15000
Ventas con el descuento aplicado: 
9000.0
22500.0
27000.0
18000.0
31500.0
13500.0


<font color='green'>Fin Actividad 1</font>

## <font color='purple'>__REFLEXIÓN GRUPAL__:<br>

confirmar si: es por notebook o al finaaaaal de todo (terminando el Módulo)

La analítica de datos ha avanzado considerablemente en los últimos años y ahora existen diversas herramientas que nos permiten realizar tareas o procesos que antes eran complicados de realizar. Gracias a su versatilidad, el lenguaje de programación Python posee una serie de librerías que permiten realizar proyectos de analítica de datos de una forma muy sencilla y una de las librerías más populares es Pandas. En este curso tuvimos la oportunidad de enfocamos en:

* Conocer los conceptos, métodos y funciones de la librería Pandas.
* Analizar datos con la librería de Pandas de forma rápida y sencilla.
* Usar la librería de Pandas para importar, construir y manipular Series y DataFrames.
* Comprobar que la librería Pandas en muy similar al uso de Excel, pero nos permite desarrollar actividades más complejas y con un mayor volúmen de datos.

__Funcionalidad y capacidades:__ Pandas es una biblioteca de análisis y manipulación de datos extremadamente poderosa en Python. Su funcionalidad incluye la capacidad de cargar, limpiar, transformar y analizar datos de manera eficiente. También ofrece numerosas funciones para realizar operaciones estadísticas y de agregación en conjuntos de datos.

__Rendimiento y escalabilidad:__ Pandas está diseñado para manejar grandes volúmenes de datos de manera eficiente. Sin embargo, al trabajar con conjuntos de datos muy grandes, es posible que se requieran técnicas adicionales, como el uso de muestras o la optimización de código, para mejorar el rendimiento. Escala de forma eficiente con otras librerías tales como Dask.

__Documentación y comunidad de usuarios:__ Pandas cuenta con una excelente documentación oficial, que incluye una guía de usuario completa, tutoriales y ejemplos de código. Además, la comunidad de usuarios de pandas es activa y colaborativa, lo que significa que hay una amplia gama de recursos y fuentes de ayuda disponibles en línea.

__Mantenimiento y actualizaciones:__ Pandas es una biblioteca madura y bien mantenida, con una comunidad de desarrollo activa. El equipo de Pandas lanza regularmente nuevas versiones que corrigen errores, agregan nuevas características y mejoran el rendimiento.

__Compatibilidad y integración:__ Pandas se integra bien con otras bibliotecas y herramientas de análisis de datos en el ecosistema de Python, como NumPy, matplotlib, Dask y scikit-learn. También es compatible con una variedad de formatos de datos, lo que facilita la importación y exportación de datos desde y hacia otras fuentes.

__Curva de aprendizaje y facilidad de uso:__ Pandas tiene una curva de aprendizaje moderada, especialmente si tienes experiencia previa con Python y estructuras de datos tabulares. La sintaxis y las operaciones de pandas pueden requerir cierta familiarización, pero una vez que te acostumbras, se vuelve una herramienta potente y flexible.

__Flexibilidad y personalización:__ Pandas ofrece una amplia gama de funcionalidades y opciones de configuración para adaptarse a diferentes requisitos y escenarios de análisis de datos. Además, Pandas es altamente extensible y permite el desarrollo de funciones personalizadas para satisfacer necesidades específicas (e.g.; métodos `apply()`y `map()`).

__Trabajo futuro__: Como equipo creemos que debemos seguir profundizando en el conocimiento de Pandas en los siguientes aspectos:
* Escalado a grandes volúmenes de datos con Dask
* Entender las dinámicas de la librería de forma tal de optimizar el rendimiento de ciertas tareas.
* Profundizar en el uso de tablas dinámicas y el uso de `loc` e `iloc`.
* Explorar más casos de usos avanzados.
* Incorporarnos a una comunidad de usuarios.

<font color='purple'>Fin reflexión grupal</font>

# **FP04. Strings**
LUIS CERDA

## Descripción del notebook

pendiente de confirmación en Miró

sdf

## <font color='purple'>__Material adicional__</font>
En el siguiente video se explica la forma en que se pueden crear Dataframes en Pandas.

In [ ]:
from IPython.display import YouTubeVideo
YouTubeVideo('https://youtu.be/GpdPvpV7MkA')

<font color='purple'>Fin material adicional </font>


## <font color='purple'> __EXPERIMENTO__: </font>

### Creación de una serie a partir de un `array` de Numpy.
La celda anterior enuncia que podríamos haber creado una serie a partir de un array NumPy; desarrollamos ese ejemplo.

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(type (a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4])

In [ ]:
s2 = pd.Series(a)
s2

0    1
1    2
2    3
3    4
dtype: int64

In [ ]:
#  Le creamos un índice
s3 = pd.Series(a, index=['A', 'B', 'C', 'D'])
s3

A    1
B    2
C    3
D    4
dtype: int64

Veamos qué pasa si le cambiamos el tipo de datos al array

In [ ]:
b = np.array([1, 2, 3, 4], dtype=np.float16)
print(type (b))
b

<class 'numpy.ndarray'>


array([1., 2., 3., 4.], dtype=float16)

In [ ]:
# y creamos una Serie
s4 = pd.Series(b, index=['A', 'B', 'C', 'D'])
s4

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float16

<font color='purple'>Fin experimento </font>

### Creación de una serie a partir de un diccionario

Si partimos de un diccionario para crear la serie:


In [ ]:
d = {"Ene":7, "Feb":5, "Mar":3}
s = pd.Series(d)
s

Ene    7
Feb    5
Mar    3
dtype: int64

El constructor utiliza las claves como etiquetas del índice, y los valores del diccionario como valores de la serie.

Si incluimos el índice explícitamente en el constructor, los valores en la serie se tomarán en el orden en el que estén en el índice explícito. Además, si en éste hay valores que no pertenecen al conjunto de claves del diccionario, se añaden a la serie con un valor *NaN*:

In [ ]:
d = {"Ene":7, "Feb":5, "Mar":3}
s = pd.Series(d, index = ["Abr", "Mar", "Feb", "Ene"])
s

Abr    NaN
Mar    3.0
Feb    5.0
Ene    7.0
dtype: float64

En este ejemplo, hemos creado la serie especificando el índice que hemos formado dando la vuelta a las claves del diccionario ("Mar", "Feb" y "Ene") y hemos añadido a la lista de etiquetas el valor "Abr", que no pertenece al conjunto de claves del diccionario. Se ha añadido a la serie, pero se le ha asignado el valor *NaN*. Es precisamente la presencia de este valor lo que modifica el tipo de la serie a float.

## <font color='green'>Actividades del notebook </font>

### Actividad 1

In [ ]:
#Solución

años = [2015,2016,2017,2018,2019,2020]
sales = [10000,25000,30000,20000,35000,15000]
sales_serie = pd.Series(sales, años)
inicio = int(input('Ingrese año inicio: '))
fin = int(input('Ingrese año fin: '))
a = 0;
for i in range(0,6):
    if inicio == años[i]:
       a = i
    elif fin == años[i]:
       b = i
       print('Ventas antes del descuento: ')
       for j in range(a,b+1):
           print(sales_serie[años[j]])
       print('Ventas con el descuento aplicado: ')
       for k in range(a,b+1):
          desc =(sales_serie[años[k]])*0.9
          print(desc)


Ingrese año inicio: 2015
Ingrese año fin: 2020
Ventas antes del descuento: 
10000
25000
30000
20000
35000
15000
Ventas con el descuento aplicado: 
9000.0
22500.0
27000.0
18000.0
31500.0
13500.0


<font color='green'>Fin Actividad 1</font>

## <font color='purple'>__REFLEXIÓN GRUPAL__:<br>

confirmar si: es por notebook o al finaaaaal de todo (terminando el Módulo)

La analítica de datos ha avanzado considerablemente en los últimos años y ahora existen diversas herramientas que nos permiten realizar tareas o procesos que antes eran complicados de realizar. Gracias a su versatilidad, el lenguaje de programación Python posee una serie de librerías que permiten realizar proyectos de analítica de datos de una forma muy sencilla y una de las librerías más populares es Pandas. En este curso tuvimos la oportunidad de enfocamos en:

* Conocer los conceptos, métodos y funciones de la librería Pandas.
* Analizar datos con la librería de Pandas de forma rápida y sencilla.
* Usar la librería de Pandas para importar, construir y manipular Series y DataFrames.
* Comprobar que la librería Pandas en muy similar al uso de Excel, pero nos permite desarrollar actividades más complejas y con un mayor volúmen de datos.

__Funcionalidad y capacidades:__ Pandas es una biblioteca de análisis y manipulación de datos extremadamente poderosa en Python. Su funcionalidad incluye la capacidad de cargar, limpiar, transformar y analizar datos de manera eficiente. También ofrece numerosas funciones para realizar operaciones estadísticas y de agregación en conjuntos de datos.

__Rendimiento y escalabilidad:__ Pandas está diseñado para manejar grandes volúmenes de datos de manera eficiente. Sin embargo, al trabajar con conjuntos de datos muy grandes, es posible que se requieran técnicas adicionales, como el uso de muestras o la optimización de código, para mejorar el rendimiento. Escala de forma eficiente con otras librerías tales como Dask.

__Documentación y comunidad de usuarios:__ Pandas cuenta con una excelente documentación oficial, que incluye una guía de usuario completa, tutoriales y ejemplos de código. Además, la comunidad de usuarios de pandas es activa y colaborativa, lo que significa que hay una amplia gama de recursos y fuentes de ayuda disponibles en línea.

__Mantenimiento y actualizaciones:__ Pandas es una biblioteca madura y bien mantenida, con una comunidad de desarrollo activa. El equipo de Pandas lanza regularmente nuevas versiones que corrigen errores, agregan nuevas características y mejoran el rendimiento.

__Compatibilidad y integración:__ Pandas se integra bien con otras bibliotecas y herramientas de análisis de datos en el ecosistema de Python, como NumPy, matplotlib, Dask y scikit-learn. También es compatible con una variedad de formatos de datos, lo que facilita la importación y exportación de datos desde y hacia otras fuentes.

__Curva de aprendizaje y facilidad de uso:__ Pandas tiene una curva de aprendizaje moderada, especialmente si tienes experiencia previa con Python y estructuras de datos tabulares. La sintaxis y las operaciones de pandas pueden requerir cierta familiarización, pero una vez que te acostumbras, se vuelve una herramienta potente y flexible.

__Flexibilidad y personalización:__ Pandas ofrece una amplia gama de funcionalidades y opciones de configuración para adaptarse a diferentes requisitos y escenarios de análisis de datos. Además, Pandas es altamente extensible y permite el desarrollo de funciones personalizadas para satisfacer necesidades específicas (e.g.; métodos `apply()`y `map()`).

__Trabajo futuro__: Como equipo creemos que debemos seguir profundizando en el conocimiento de Pandas en los siguientes aspectos:
* Escalado a grandes volúmenes de datos con Dask
* Entender las dinámicas de la librería de forma tal de optimizar el rendimiento de ciertas tareas.
* Profundizar en el uso de tablas dinámicas y el uso de `loc` e `iloc`.
* Explorar más casos de usos avanzados.
* Incorporarnos a una comunidad de usuarios.

<font color='purple'>Fin reflexión grupal</font>

# Clase 1

# Desarrollo de actividad 1

## Caso 1. Importación de librerías en lineas separadas

### Sí

In [ ]:
import pandas as pd
import sys
import os

### No

In [ ]:
import pandas, sys, os

<font color='green'>Fin actividad 1</font>

## Caso 2. Más de un espacio para alinear el código

### SÍ

In [ ]:
x=1
y=2
both=1+2
print(both)

3


### NO

In [ ]:
x=     1
y=     2
both=1+2
print(both)

3


## Caso 3. Identación (*alineación*)

### SÍ

In [ ]:
for i in range(1,5):
  if i <= 2:
    print(f'{i} es menor o igual a 2')
  else:
    print(f'{i} es mayor que 2')

1 es menor o igual a 2
2 es menor o igual a 2
3 es mayor que 2
4 es mayor que 2


### NO *(error de identacion en los print)*

In [ ]:
'''
Código comentado para no generar error

for i in range(8):
  if i <= 5:
  print(f'{i} es menor o igual a 5')
  else:
  print(f'{i} es mayor que 5')
'''

"\nCódigo comentado para no generar error\n\nfor i in range(8):\n  if i <= 5:\n  print(f'{i} es menor o igual a 5')\n  else:\n  print(f'{i} es mayor que 5')\n"